// ip/cores/eclass/rtl/eclass_top.sv
//
// GENERATED by scripts/gen_wrapper.py from gen/vlog/mkeclass_axi4lite.v -- DO NOT EDIT BY HAND.
// Regenerate with:  python3 ip/cores/eclass/scripts/gen_wrapper.py
//
// Structural wrapper: mkeclass_axi4lite plus a reset synchronizer. The core is instantiated
// BYTE-IDENTICAL and unmodified; MANIFEST.sha256 still covers it.
//
// The ONLY functional change at the boundary is what RST_N drives. Before, it fed 1,450 async pins
// directly and reset deassertion was unconstrained, which measured 41 removal endpoints below zero
// (worst -0.622 ns). Now it feeds exactly 3 flops -- the synchronizer -- and every other async pin
// sees rst_n_sync, which is launched by a flop on CLK and therefore shares the clock insertion
// delay with its capture flops.
//
// RST_N's CONTRACT at this boundary: asynchronous, active low, released at any phase you like.
// That is strictly easier for an integrator to honour than the previous unstated requirement, and
// impossible to get silently wrong.
//
// Ports are identical to the core: same names, widths, directions. See tests/test_top_ports.py.

module eclass_top(
  resetpc,
  CLK,
  RST_N,
  master_d_awvalid,
  master_d_awaddr,
  master_d_awprot,
  master_d_awsize,
  master_d_m_awready_awready,
  master_d_wvalid,
  master_d_wdata,
  master_d_wstrb,
  master_d_m_wready_wready,
  master_d_m_bvalid_bvalid,
  master_d_m_bvalid_bresp,
  master_d_bready,
  master_d_arvalid,
  master_d_araddr,
  master_d_arprot,
  master_d_arsize,
  master_d_m_arready_arready,
  master_d_m_rvalid_rvalid,
  master_d_m_rvalid_rresp,
  master_d_m_rvalid_rdata,
  master_d_rready,
  master_i_awvalid,
  master_i_awaddr,
  master_i_awprot,
  master_i_awsize,
  master_i_m_awready_awready,
  master_i_wvalid,
  master_i_wdata,
  master_i_wstrb,
  master_i_m_wready_wready,
  master_i_m_bvalid_bvalid,
  master_i_m_bvalid_bresp,
  master_i_bready,
  master_i_arvalid,
  master_i_araddr,
  master_i_arprot,
  master_i_arsize,
  master_i_m_arready_arready,
  master_i_m_rvalid_rvalid,
  master_i_m_rvalid_rresp,
  master_i_m_rvalid_rdata,
  master_i_rready,
  sb_clint_msip_put,
  EN_sb_clint_msip_put,
  RDY_sb_clint_msip_put,
  sb_clint_mtip_put,
  EN_sb_clint_mtip_put,
  RDY_sb_clint_mtip_put,
  sb_clint_mtime_put,
  EN_sb_clint_mtime_put,
  RDY_sb_clint_mtime_put,
  sb_ext_interrupt_put,
  EN_sb_ext_interrupt_put,
  RDY_sb_ext_interrupt_put
);

  input wire [31 : 0] resetpc;
  input wire CLK;
  input wire RST_N;
  output wire master_d_awvalid;
  output wire [31 : 0] master_d_awaddr;
  output wire [2 : 0] master_d_awprot;
  output wire [1 : 0] master_d_awsize;
  input wire master_d_m_awready_awready;
  output wire master_d_wvalid;
  output wire [31 : 0] master_d_wdata;
  output wire [3 : 0] master_d_wstrb;
  input wire master_d_m_wready_wready;
  input wire master_d_m_bvalid_bvalid;
  input wire [1 : 0] master_d_m_bvalid_bresp;
  output wire master_d_bready;
  output wire master_d_arvalid;
  output wire [31 : 0] master_d_araddr;
  output wire [2 : 0] master_d_arprot;
  output wire [1 : 0] master_d_arsize;
  input wire master_d_m_arready_arready;
  input wire master_d_m_rvalid_rvalid;
  input wire [1 : 0] master_d_m_rvalid_rresp;
  input wire [31 : 0] master_d_m_rvalid_rdata;
  output wire master_d_rready;
  output wire master_i_awvalid;
  output wire [31 : 0] master_i_awaddr;
  output wire [2 : 0] master_i_awprot;
  output wire [1 : 0] master_i_awsize;
  input wire master_i_m_awready_awready;
  output wire master_i_wvalid;
  output wire [31 : 0] master_i_wdata;
  output wire [3 : 0] master_i_wstrb;
  input wire master_i_m_wready_wready;
  input wire master_i_m_bvalid_bvalid;
  input wire [1 : 0] master_i_m_bvalid_bresp;
  output wire master_i_bready;
  output wire master_i_arvalid;
  output wire [31 : 0] master_i_araddr;
  output wire [2 : 0] master_i_arprot;
  output wire [1 : 0] master_i_arsize;
  input wire master_i_m_arready_arready;
  input wire master_i_m_rvalid_rvalid;
  input wire [1 : 0] master_i_m_rvalid_rresp;
  input wire [31 : 0] master_i_m_rvalid_rdata;
  output wire master_i_rready;
  input wire sb_clint_msip_put;
  input wire EN_sb_clint_msip_put;
  output wire RDY_sb_clint_msip_put;
  input wire sb_clint_mtip_put;
  input wire EN_sb_clint_mtip_put;
  output wire RDY_sb_clint_mtip_put;
  input wire [63 : 0] sb_clint_mtime_put;
  input wire EN_sb_clint_mtime_put;
  output wire RDY_sb_clint_mtime_put;
  input wire sb_ext_interrupt_put;
  input wire EN_sb_ext_interrupt_put;
  output wire RDY_sb_ext_interrupt_put;

  wire rst_n_sync;

  eclass_reset_sync #(.STAGES(3)) u_rst_sync (
    .clk(CLK),
    .arst_n(RST_N),
    .rst_n_sync(rst_n_sync)
  );

  mkeclass_axi4lite u_core (
    .resetpc(resetpc),
    .CLK(CLK),
    .RST_N(rst_n_sync),
    .master_d_awvalid(master_d_awvalid),
    .master_d_awaddr(master_d_awaddr),
    .master_d_awprot(master_d_awprot),
    .master_d_awsize(master_d_awsize),
    .master_d_m_awready_awready(master_d_m_awready_awready),
    .master_d_wvalid(master_d_wvalid),
    .master_d_wdata(master_d_wdata),
    .master_d_wstrb(master_d_wstrb),
    .master_d_m_wready_wready(master_d_m_wready_wready),
    .master_d_m_bvalid_bvalid(master_d_m_bvalid_bvalid),
    .master_d_m_bvalid_bresp(master_d_m_bvalid_bresp),
    .master_d_bready(master_d_bready),
    .master_d_arvalid(master_d_arvalid),
    .master_d_araddr(master_d_araddr),
    .master_d_arprot(master_d_arprot),
    .master_d_arsize(master_d_arsize),
    .master_d_m_arready_arready(master_d_m_arready_arready),
    .master_d_m_rvalid_rvalid(master_d_m_rvalid_rvalid),
    .master_d_m_rvalid_rresp(master_d_m_rvalid_rresp),
    .master_d_m_rvalid_rdata(master_d_m_rvalid_rdata),
    .master_d_rready(master_d_rready),
    .master_i_awvalid(master_i_awvalid),
    .master_i_awaddr(master_i_awaddr),
    .master_i_awprot(master_i_awprot),
    .master_i_awsize(master_i_awsize),
    .master_i_m_awready_awready(master_i_m_awready_awready),
    .master_i_wvalid(master_i_wvalid),
    .master_i_wdata(master_i_wdata),
    .master_i_wstrb(master_i_wstrb),
    .master_i_m_wready_wready(master_i_m_wready_wready),
    .master_i_m_bvalid_bvalid(master_i_m_bvalid_bvalid),
    .master_i_m_bvalid_bresp(master_i_m_bvalid_bresp),
    .master_i_bready(master_i_bready),
    .master_i_arvalid(master_i_arvalid),
    .master_i_araddr(master_i_araddr),
    .master_i_arprot(master_i_arprot),
    .master_i_arsize(master_i_arsize),
    .master_i_m_arready_arready(master_i_m_arready_arready),
    .master_i_m_rvalid_rvalid(master_i_m_rvalid_rvalid),
    .master_i_m_rvalid_rresp(master_i_m_rvalid_rresp),
    .master_i_m_rvalid_rdata(master_i_m_rvalid_rdata),
    .master_i_rready(master_i_rready),
    .sb_clint_msip_put(sb_clint_msip_put),
    .EN_sb_clint_msip_put(EN_sb_clint_msip_put),
    .RDY_sb_clint_msip_put(RDY_sb_clint_msip_put),
    .sb_clint_mtip_put(sb_clint_mtip_put),
    .EN_sb_clint_mtip_put(EN_sb_clint_mtip_put),
    .RDY_sb_clint_mtip_put(RDY_sb_clint_mtip_put),
    .sb_clint_mtime_put(sb_clint_mtime_put),
    .EN_sb_clint_mtime_put(EN_sb_clint_mtime_put),
    .RDY_sb_clint_mtime_put(RDY_sb_clint_mtime_put),
    .sb_ext_interrupt_put(sb_ext_interrupt_put),
    .EN_sb_ext_interrupt_put(EN_sb_ext_interrupt_put),
    .RDY_sb_ext_interrupt_put(RDY_sb_ext_interrupt_put)
  );

endmodule
