#!/usr/bin/env bash
# ============================================================================================
#  ⚠️  THIS IS THE KLAYOUT LVS PATH, AND IT DOES **NOT** WORK FOR THIS DESIGN.
#
#  Retained only as documented evidence of a measured negative result. For the flow that
#  actually produces a clean LVS, use:  scripts/signoff/lvs/   (magic extract + netgen compare)
#  and read docs/LVS_FLOW.md.
#
#  WHY IT FAILS: in hierarchical mode KLayout builds a circuit for EVERY cell it finds in the
#  layout, and its SPICE reader cannot create a circuit for a DEVICE-FREE subcircuit. gf180's
#  fill_*/filltie/endcap have empty .SUBCKT bodies, so they can never match -- the run returns
#  "Mismatch 10, NoMatch 91" on exactly ANTENNA/ENDCAP/FILLTIE/FILL_*, and the gf180 KLayout deck
#  ships no flatten/ignore lever. Adding all 80,080 physical cells to the schematic produces a
#  BYTE-IDENTICAL failure.
# ============================================================================================
# designs/eclass_gf180/scripts/run_lvs.sh — real gf180mcu KLayout LVS on the signed-off GDS.
#
# This is REAL LVS, not a substitute. It is available here because gf180mcu is an actual foundry
# PDK with an open LVS deck and open standard-cell SPICE -- unlike the ASAP7 flagship, where no LVS
# deck exists and the project had to fall back on a connectivity + formal-equivalence substitute.
#
# The schematic side is generated by scripts/v2spice.py, which takes cell pin ORDER from the PDK's
# own .SUBCKT lines. Do not replace it with a generic Verilog->SPICE writer: SPICE subcircuit calls
# are positional, and a generator that used liberty/Verilog port order would produce a netlist that
# parses fine and then fails LVS everywhere for a reason that has nothing to do with the layout.
set -euo pipefail
PROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
PDK="${GF180_PDK:-$HOME/.volare/volare/gf180mcu/versions/c6d73a35f524070e85faff4a6a9eef49553ebc2b}"
D=designs/eclass_gf180
GDS="${1:-/work/$D/signoff/eclass_gf180_signoff_25mhz.gds}"
OUT="${2:-/work/$D/pv/lvs}"

[ -d "$PDK" ] || { echo "gf180mcu PDK not found at $PDK"; exit 1; }
if docker ps --format '{{.Names}}' | grep -qE '^eclass-(lvs|drc)$'; then
  echo "an eclass DRC/LVS run is already active — refusing to start a second"; exit 1
fi

# Regenerate the schematic netlist from the signed-off netlist every time, so the schematic can
# never silently drift from the layout it is being compared against.
mkdir -p "$PROOT/$D/pv/lvs"
python3 "$PROOT/$D/scripts/v2spice.py" \
  "$PROOT/$D/signoff/eclass_gf180_signoff.v" \
  "$PDK/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu9t5v0/spice/gf180mcu_fd_sc_mcu9t5v0.spice" \
  "$PROOT/$D/pv/lvs/eclass_gf180.spice"

# The .include path inside the generated netlist is a HOST path; rewrite it to the container mount.
# Getting this wrong does not fail at generation time -- it fails HOURS later inside LVS with
# "Unable to open file ... line 2 in Netlist::read", which is exactly what happened on the first run.
sed -i.bak "s#$PDK#/pdk#g" "$PROOT/$D/pv/lvs/eclass_gf180.spice"

# Physical-only, DEVICE-BEARING cells (the antenna diodes ORFS inserts during routing) exist in the
# layout but never in the Verilog netlist. Without them LVS reports "Netlists don't match" and names
# `CIRCUIT (none) vs ...__ANTENNA`. Fill/tap/endcap are physical-only too but extract as no-device
# structures, so they must NOT be added.
docker run --rm -v "$PROOT:/work" -e SIGNOFF_NICK="${SIGNOFF_NICK:-eclass_gf180_mc}" \
  -w /OpenROAD-flow-scripts/flow orfs-arm64:local bash -lc \
  "source /OpenROAD-flow-scripts/env.sh && openroad -exit /work/$D/scripts/emit_phys_cells.tcl" \
  2>/dev/null | grep "^PHYSCELL " | sed "s/^PHYSCELL //" > /tmp/physcells.spice || true
if [ -s /tmp/physcells.spice ]; then
  python3 "$PROOT/$D/scripts/add_phys_cells.py" \
    "$PROOT/$D/pv/lvs/eclass_gf180.spice" /tmp/physcells.spice
fi

docker run --rm --cpus=7 --memory=20g --name eclass-lvs \
  -v "$PROOT:/work" -v "$PDK:/pdk:ro" -w /work orfs-arm64:local bash -lc "
    set -e
    pip install --quiet docopt klayout
    python3 /pdk/gf180mcuC/libs.tech/klayout/lvs/run_lvs.py \
      --layout=$GDS \
      --netlist=/work/$D/pv/lvs/eclass_gf180.spice \
      --variant=C --topcell=mkeclass_axi4lite \
      --run_mode=deep --lvs_sub=VSS --run_dir=$OUT
  "
