"""Emit ip/cores/eclass/rtl/eclass_top.sv from the core's own generated Verilog.

WHY GENERATED: the core has 57 ports / 421 bits. A hand-transcribed wrapper with one swapped bus
direction or one mistyped width presents as a fetch hang -- indistinguishable from a broken core,
and it would burn the milestone chasing the wrong thing. The same reasoning already governs
sim/gen_binding.py.

The declarations are copied VERBATIM from the core (including the exact [msb:lsb] text) rather than
reconstructed from a width, so a reversed range cannot be introduced by this script. RST_N is the
single deliberate exception: it stays a port, but inside it drives only the synchronizer.

Emits Verilog-2001 non-ANSI style to mirror bsc output exactly.
"""
import pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
CORE_V = HERE.parent / "gen" / "vlog" / "mkeclass_axi4lite.v"
OUT = HERE.parent / "rtl" / "eclass_top.sv"
CORE_TOP = "mkeclass_axi4lite"
WRAPPER_TOP = "eclass_top"
STAGES = 3

HEADER = f"""// ip/cores/eclass/rtl/{WRAPPER_TOP}.sv
//
// GENERATED by scripts/gen_wrapper.py from gen/vlog/{CORE_TOP}.v -- DO NOT EDIT BY HAND.
// Regenerate with:  python3 ip/cores/eclass/scripts/gen_wrapper.py
//
// Structural wrapper: {CORE_TOP} plus a reset synchronizer. The core is instantiated
// BYTE-IDENTICAL and unmodified; MANIFEST.sha256 still covers it.
//
// The ONLY functional change at the boundary is what RST_N drives. Before, it fed 1,450 async pins
// directly and reset deassertion was unconstrained, which measured 41 removal endpoints below zero
// (worst -0.622 ns). Now it feeds exactly 3 flops -- the synchronizer -- and every other async pin
// sees rst_n_sync, which is launched by a flop on CLK and therefore shares the clock insertion
// delay with its capture flops.
//
// RST_N's CONTRACT at this boundary: asynchronous, active low, released at any phase you like.
// That is strictly easier for an integrator to honour than the previous unstated requirement, and
// impossible to get silently wrong.
//
// Ports are identical to the core: same names, widths, directions. See tests/test_top_ports.py.
"""


def main():
    src = CORE_V.read_text()
    m = re.search(rf"^module\s+{CORE_TOP}\s*\((.*?)\);", src, re.S | re.M)
    if not m:
        sys.exit(f"core top {CORE_TOP} not found in {CORE_V}")
    body = src[m.end():]
    names = [p.strip() for p in m.group(1).split(",") if p.strip()]

    decls, unresolved = [], []
    for name in names:
        d = re.search(rf"^\s*(input|output|inout)\s*(\[\s*\d+\s*:\s*\d+\s*\])?\s*"
                      rf"{re.escape(name)}\s*;", body, re.M)
        if not d:
            unresolved.append(name)
            continue
        rng = f" {d.group(2)}" if d.group(2) else ""
        decls.append(f"  {d.group(1)} wire{rng} {name};")

    if unresolved:
        sys.exit("UNRESOLVED port declarations (resolve deliberately, do not guess): "
                 + ", ".join(unresolved))
    if "RST_N" not in names or "CLK" not in names:
        sys.exit("core is missing CLK or RST_N -- the wrapper's premise is wrong, refusing to emit")

    conns = []
    for name in names:
        conns.append("    .RST_N(rst_n_sync)" if name == "RST_N" else f"    .{name}({name})")

    text = HEADER + "\n"
    text += f"module {WRAPPER_TOP}(\n"
    text += ",\n".join(f"  {n}" for n in names)
    text += "\n);\n\n"
    text += "\n".join(decls) + "\n\n"
    text += "  wire rst_n_sync;\n\n"
    text += f"  eclass_reset_sync #(.STAGES({STAGES})) u_rst_sync (\n"
    text += "    .clk(CLK),\n    .arst_n(RST_N),\n    .rst_n_sync(rst_n_sync)\n  );\n\n"
    text += f"  {CORE_TOP} u_core (\n" + ",\n".join(conns) + "\n  );\n\n"
    text += "endmodule\n"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT} -- {len(names)} ports")


if __name__ == "__main__":
    main()
